version: '3.8'

services:
  app:
    build: .
    ports:
      - "5050:5050"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/suomisf?sslmode=disable
      - ENVIRONMENT=development
      - PORT=5050
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: suomisf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres_data:
